version: '3.7'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoserver
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    image: mongo:latest
    container_name: mongoserver
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: demodb  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network
    deploy:
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '1'
  neo4j:
    image: neo4j:latest
    container_name: neo4jserver
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - $HOME/neo4j/data10:/data
      - $HOME/neo4j/logs:/logs
    networks:
      - mongo-compose-network
networks: 
  mongo-compose-network:
      driver: bridge
volumes:
  mongodb_data_container:
    
